# Generated by Django 5.1.1 on 2024-10-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverlyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('describtion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NavList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_pos_name', models.CharField(max_length=255)),
                ('dev_name', models.CharField(max_length=255)),
                ('dev_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='')),
                ('describtion', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_center', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('developers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.navlist')),
            ],
        ),
    ]
